# Uncomment the next line to define a global platform for your project
platform :osx, '13.0'

USE_EXTERNAL_SPDLOG = 0


REPO_ROOT_PATH = File.expand_path('../../')
PROJECT_ROOT_PATH = File.expand_path('.')
THIRDPARTY_ROOT_PATH = REPO_ROOT_PATH + '/thirdParty'
THIRDPARTY_BUILD_PATH = REPO_ROOT_PATH + '/build'

puts REPO_ROOT_PATH
puts PROJECT_ROOT_PATH
puts THIRDPARTY_BUILD_PATH
puts THIRDPARTY_ROOT_PATH

target 'SimplePlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pre_install do |installer|
    # 用于执行命令的工具函数，如果命令失败，立即退出脚本并显示错误信息
    run_or_abort = lambda do |args, err_msg|
      system(*args) or abort(err_msg)
    end

    # spdlog
    # spdlog可以是header only导入，但如果提前编译，可以大大加快项目编译速度
    run_or_abort.call(['cmake', '-S', THIRDPARTY_ROOT_PATH + '/spdlog/', '-B', THIRDPARTY_BUILD_PATH + '/thirdParty/spdlog/'], 'cmake configure spdlog failed')
    run_or_abort.call(['cmake', '--build', THIRDPARTY_BUILD_PATH + '/thirdParty/spdlog/'], 'cmake build spdlog failed')

    # FFMpeg
    ff_build_dir = THIRDPARTY_BUILD_PATH + '/thirdParty/FFMpeg'
    ff_lib_path = File.join(ff_build_dir, 'lib', 'libavformat.a')

    if File.exist?(ff_lib_path)
      puts ff_lib_path + ' 已存在'
    else
      puts ff_lib_path + ' 缺失，重新编译...'
      ENV['FF_SOURCE_DIR'] = THIRDPARTY_ROOT_PATH + '/FFMpeg'
      ENV['FF_BUILD_DIR'] = ff_build_dir

      run_or_abort.call(['sh', THIRDPARTY_ROOT_PATH + '/build_script/build_FFMpeg.sh'], 'build_FFMpeg.sh failed')
    end

    # glm
    # glm是header only引入，无需编译
    # system('cmake', '-S', THIRDPARTY_ROOT_PATH + '/glm/', '-B', THIRDPARTY_BUILD_PATH + '/thirdParty/glm/')
    # system('cmake', '--build', THIRDPARTY_BUILD_PATH + '/thirdParty/glm/')

  end
  
  # if USE_EXTERNAL_SPDLOG
  #   pod 'spdlog'
  # else
  #   pod 'spdlog', :path => THIRDPARTY_ROOT_PATH + 'spdlog'
  # end

  pod 'SimplePlayer', :path => '../../', :subspec => ['Base', 'Ability', 'Engine', 'Interface','spdlog', 'FFMpeg', 'glm']


  
end
